export const homeWheels = [
  "/wheels2/redwhite.modular1.webp",
  "/wheels2/green.modular1.webp",
  "/wheels2/silver.flow1.webp",
];

export interface Wheel {
  id: number;
  name: string;
  price: number;
  currency: string;
  images: string[];
  buttonColor: string;
  cardBg: string;
  category: string;
  size: string[];
  compatibleCars: string[];
  description: string;
  specs: string[];
}

export const wheels: Wheel[] = [
  {
    id: 1,
    name: "Deep Concave Gunmetal",
    price: 360,
    currency: "euro",
    images: [
      "deepconcavegri.webp",
      "deepconcavegri2.performance.webp",
      "deepconavegri3.webp",
    ],
    buttonColor: "#888888",
    cardBg: "#dddddd",
    category: "Performance",
    size: ["22", "21", "19"],
    compatibleCars: ["Mercedes", "Audi", "Seat", "VW"],
    description: "Model: ZP4.1 Deep Concave | Gunmetal",
    specs: [
      "Design: concave wheel, 5 doublespokes with deep undercutting",
      "Finish: gunmetal painted",
      "Production Technique: low pressure cast",
      "Wheel Cap: Z-Performance logo printed on carbon fibre background",
    ],
  },
  {
    id: 2,
    name: "Deep Concave Custom Finish Satin Black",
    price: 477,
    currency: "euro",
    images: [
      "satinblack.performance1.webp",
      "satinblack.performance2.webp",
      "satinblack.performance3.webp",
    ],
    buttonColor: "#444444",
    cardBg: "#bbbbbb",
    category: "Performance",
    size: ["22", "21", "19"],
    compatibleCars: ["BMW", "Mercedes"],
    description: "Model: ZP.09 Deep Concave | Custom Finish Satin Black",
    specs: [
      "Design: concave wheel, multispoke - deep undercutting",
      "Finish: satin black painted",
      "Production Technique: low pressure cast",
      "Wheel Cap: Z-Performance Logo | Premium Collection",
    ],
  },
  {
    id: 3,
    name: "Deep Concave Custom Satin Black",
    price: 420,
    currency: "euro",
    images: [
      "satinblackcustom.performance1.webp",
      "satinblackcustom.performance2.webp",
      "satinblackcustom.performance3.webp",
    ],
    buttonColor: "#5c5b57",
    cardBg: "#b6b5ad",
    category: "Performance",
    size: ["22", "21", "19"],
    compatibleCars: ["Audi", "VW", "Mercedes"],
    description: "Model: ZP6.1 Deep Concave | Custom Satin Black",
    specs: [
      "Design: deep concave wheel, 5 pokes with deep undercutting",
      "Finish: satin black painted",
      "Production Technique: low pressure cast",
      "Wheel Cap: Alloy, Z-Performance logo",
    ],
  },
  {
    id: 4,
    name: "Deep Concave Sparkling Silver",
    price: 477,
    currency: "euro",
    images: [
      "sparklingsilver.performance1.webp",
      "sparklingsilver.performance2.webp",
      "sparklingsilver.performance3.webp",
    ],
    buttonColor: "#c0c0c0",
    cardBg: "#f4f4f4",
    category: "Performance",
    size: ["22", "21", "19"],
    compatibleCars: ["Audi", "VW", "Mercedes"],
    description: "Model: ZP.09 Deep Concave | Sparkling Silver",
    specs: [
      "Design: concave wheel, multispoke - deep undercutting",
      "Finish: sparkling silver painted",
      "Production Technique: low pressure cast",
      "Wheel Cap: Z-Performance Logo | Premium Collection",
    ],
  },
  {
    id: 5,
    name: "FlowForged Blood Red",
    price: 699,
    currency: "euro",
    images: [
      "bloodred.flow1.webp",
      "bloodred.flow2.webp",
      "bloodred.flow3.webp",
    ],
    buttonColor: "#8B0000",
    cardBg: "#FFE4E1",
    category: "Flow",
    size: ["22", "21", "20"],
    compatibleCars: ["BMW", "Mercedes", "Audi"],
    description: "Model: ZF2.1 FlowForged | Blood Red",
    specs: [
      "Design: flow-formed wheel with dynamic spokes",
      "Finish: blood red painted",
      "Production Technique: flow forming",
      "Wheel Cap: Z-Performance logo with red accent",
    ],
  },
  {
    id: 6,
    name: "FlowForged Candy Red",
    price: 659,
    currency: "euro",
    images: [
      "candyred.flow1.webp",
      "candyred.flow2.webp",
      "candyred.flow3.webp",
    ],
    buttonColor: "#DC143C",
    cardBg: "#FFF0F5",
    category: "Flow",
    size: ["21", "20", "19"],
    compatibleCars: ["Mercedes", "BMW", "VW"],
    description: "Model: ZF1.8 FlowForged | Candy Red",
    specs: [
      "Design: lightweight flow-formed construction",
      "Finish: candy red metallic",
      "Production Technique: advanced flow forming",
      "Wheel Cap: Premium Z-Performance logo",
    ],
  },
  {
    id: 7,
    name: "FlowForged Champagne",
    price: 629,
    currency: "euro",
    images: [
      "champagne.flow1.webp",
      "champagne.flow2.webp",
      "champagne.flow3.webp",
    ],
    buttonColor: "#F7E7CE",
    cardBg: "#FDF5E6",
    category: "Flow",
    size: ["22", "21", "20"],
    compatibleCars: ["Audi", "Mercedes", "BMW"],
    description: "Model: ZF3.2 FlowForged | Champagne",
    specs: [
      "Design: elegant flow-formed wheel",
      "Finish: champagne metallic",
      "Production Technique: precision flow forming",
      "Wheel Cap: Gold-accented Z-Performance logo",
    ],
  },
  {
    id: 8,
    name: "FlowForged Silver",
    price: 599,
    currency: "euro",
    images: ["silver.flow1.webp", "silver.flow2.webp", "silver.flow3.webp"],
    buttonColor: "#C0C0C0",
    cardBg: "#F8F8FF",
    category: "Flow",
    size: ["21", "20", "19"],
    compatibleCars: ["BMW", "Audi", "VW"],
    description: "Model: ZF2.5 FlowForged | Silver",
    specs: [
      "Design: classic flow-formed design",
      "Finish: silver metallic",
      "Production Technique: flow forming technology",
      "Wheel Cap: Silver Z-Performance logo",
    ],
  },
  {
    id: 9,
    name: "Modular Blue",
    price: 549,
    currency: "euro",
    images: ["blue.modular1.webp", "blue.modular2.webp", "blue.modular3.webp"],
    buttonColor: "#0066CC",
    cardBg: "#E6F3FF",
    category: "Modular",
    size: ["20", "19", "18"],
    compatibleCars: ["BMW", "Mercedes", "Audi"],
    description: "Model: ZM1.5 Modular | Blue",
    specs: [
      "Design: modular construction with removable elements",
      "Finish: electric blue painted",
      "Production Technique: modular assembly",
      "Wheel Cap: Blue-accented Z-Performance logo",
    ],
  },
  {
    id: 10,
    name: "Modular Green",
    price: 569,
    currency: "euro",
    images: [
      "green.modular1.webp",
      "green.modular2.webp",
      "green.modular3.webp",
    ],
    buttonColor: "#228B22",
    cardBg: "#F0FFF0",
    category: "Modular",
    size: ["20", "19", "18"],
    compatibleCars: ["Audi", "VW", "Mercedes"],
    description: "Model: ZM2.1 Modular | Green",
    specs: [
      "Design: customizable modular wheel system",
      "Finish: forest green metallic",
      "Production Technique: precision modular construction",
      "Wheel Cap: Green Z-Performance logo",
    ],
  },
  {
    id: 11,
    name: "Modular Pink",
    price: 579,
    currency: "euro",
    images: ["pink.modular1.webp", "pink.modular2.webp", "pink.modular3.webp"],
    buttonColor: "#FF69B4",
    cardBg: "#FFF0F5",
    category: "Modular",
    size: ["19", "18", "17"],
    compatibleCars: ["BMW", "Mercedes", "VW"],
    description: "Model: ZM1.8 Modular | Pink",
    specs: [
      "Design: bold modular design with pink accents",
      "Finish: hot pink metallic",
      "Production Technique: advanced modular system",
      "Wheel Cap: Pink-highlighted Z-Performance logo",
    ],
  },
  {
    id: 12,
    name: "Modular Red & White",
    price: 589,
    currency: "euro",
    images: [
      "redwhite.modular1.webp",
      "redwhite.modular2.webp",
      "redwhite.modular3.webp",
    ],
    buttonColor: "#FF0000",
    cardBg: "#FFEBEE",
    category: "Modular",
    size: ["20", "19", "18"],
    compatibleCars: ["Mercedes", "BMW", "Audi"],
    description: "Model: ZM3.0 Modular | Red & White",
    specs: [
      "Design: dual-tone modular construction",
      "Finish: red and white two-tone",
      "Production Technique: precision dual-color modular",
      "Wheel Cap: Dual-tone Z-Performance logo",
    ],
  },
];
